import AuthBackground from "components/global/UI/Background";
import ButtonDetails from "components/global/UI/ButtonDetails";
import TextDetails from "components/global/UI/TextDetails";
import { createOrJoinParish } from "constants/parish";
import Head from "next/head";
import Link from "next/link";
import styled from "styled-components";
import { useEffect } from "react";
import { fetchUserData } from "store/auth-slice";
import { useDispatch, useSelector } from "react-redux";
import { AppDispatch } from "store/store";

const Parish = () => {
  const dispatch = useDispatch<AppDispatch>();
  console.log("asd");

  const isAuthenticated =
    useSelector((state: any) => state.auth.token) !== null ? true : false;

  useEffect(() => {
    if (isAuthenticated === null) return;
    dispatch(fetchUserData());
    console.log("app running");
  });
  return (
    <>
      <Head>
        <title>eparafia</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <AuthBackground>
        <ContainerStyle>
          <div>
            <TextDetails
              text={createOrJoinParish.text}
              size="large"
              weight="large"
              underline={true}
            />
            <TextDetails text={createOrJoinParish.description} size="medium" />
          </div>
          <div>
            <Link href="/parish/create-parish">
              <ButtonDetails
                text={createOrJoinParish.buttonText}
                color="secondary"
              ></ButtonDetails>
            </Link>
          </div>
        </ContainerStyle>
      </AuthBackground>
    </>
  );
};

export default Parish;

const ContainerStyle = styled.div`
  display: flex;
  flex-direction: row;
  width: 60vw;
  div {
    width: 50%;
    display: flex;
    flex-direction: column;
    justify-content: center;
  }
  p {
    margin: 30px 30px 100px 30px;
  }
  button {
    border: 1px solid black;
    border-radius: 10px;
    padding: 25px;
    margin: 10px;
    font-size: 40px;
    width: 100%;
    cursor: pointer;
  }
`;
