import type { AppProps } from "next/app";
import { Html } from "next/document";
import Head from "next/head";
import { useEffect } from "react";
import { ThemeProvider } from "styled-components";
import GlobalStyle from "styles/global-style";
import { theme } from "styles/theme";

export default function App({ Component, pageProps }: AppProps) {
  useEffect(() => {
    console.log("run app");
  }, []);

  return (
    <>
      <Head>
        <title>eparafia</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme}>
        <Component {...pageProps} />
        <GlobalStyle />
      </ThemeProvider>
    </>
  );
}
